baseURL = "http://socion4x4.ru/"
languageCode = "en-us"
title = "Боевая соционика"
theme = "nla"
MetaDataFormat = "toml"
Paginate = 10

[taxonomies]
    category = "categories"
    tag = "tags"

[[menu.main]]
    name = "АРХЕТИПЫ"
    weight = -100
    url = "/archetype/"
[[menu.main]]
    name = "СТАТЬИ"
    weight = -100
    url = "/post/"
#[[menu.main]]
#    name = "КУРСЫ"
#    weight = -100
#    url = "/course/"
