baseURL = "http://edubot.pro/"
languageCode = "en-us"
title = "Боевая соционика"
theme = "nla"
MetaDataFormat = "toml"
Paginate = 10

[taxonomies]
    tag = "tags"
    coursetag = "coursetags"

[[menu.main]]
    name = "АРХЕТИПЫ"
    weight = -100
    url = "/archetype/"
#[[menu.main]]
#    name = "БЛОГ"
#    weight = -100
#    url = "/post/"
#[[menu.main]]
#    name = "КУРСЫ"
#    weight = -100
#    url = "/course/"
